### ISSUE TITLE
TASK - Appointment cancel feature for doctors

### ISSUE THREAD

**Issue by DrakeHunterK7** [AC159/SOEN_390#82] opened 2022-03-22 04:57 UTC
Add functionality for a doctor to be able to cancel their previously created appointment. Cancellation should send a notification to the patient with whom the appointment was originally set.

**Comment by BunnyPrince** [comment] 2022-04-07 03:48
Is a duplicate of #93 so it will be closed

**Closed by BunnyPrince** 2022-04-07 03:48 UTC
Labels: Medical Doctor, task
